services:
  locopycat:
    build: .
    container_name: locopycat
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data/server_keys:/app/keys